# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

#  config.vm.provision "ansible" do |ansible|
#    ansible.playbook = "provisioning/vpn.yml"
#    ansible.become = "true"
#  end


  config.vm.define "inetRouter" do |inetRouter|
    inetRouter.vm.hostname = "inetRouter"
    inetRouter.vm.network "private_network", adapter: 2, virtualbox__intnet: "rr"
    inetRouter.vm.network "private_network", adapter: 3, virtualbox__intnet: "rr"
    inetRouter.vm.provider :virtualbox do |vb|
      vb.name = "inetRouter"
	  vb.memory = 256
    end
  end

  config.vm.define "centralRouter" do |centralRouter|
    centralRouter.vm.hostname = "centralRouter"
    centralRouter.vm.network "private_network", adapter: 2, virtualbox__intnet: "rr"
    centralRouter.vm.network "private_network", adapter: 3, virtualbox__intnet: "rr"
    centralRouter.vm.network "private_network", ip: "172.16.2.1", adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "Server"
    centralRouter.vm.provider :virtualbox do |vb|
      vb.name = "centralRouter"
	  vb.memory = 256
    end
    centralRouter.vm.provision "shell", run: "always", inline: <<-SHELL
    ip route del default dev eth0
    SHELL
  end

  config.vm.define "testServer1" do |testServer1|
    testServer1.vm.hostname = "testServer1"
    testServer1.vm.network "private_network", ip: "172.16.2.2", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "Server"
    testServer1.vm.network "private_network",adapter: 3, virtualbox__intnet: "Client"
    testServer1.vm.provider :virtualbox do |vb|
      vb.name = "testServer1"
      vb.memory = 256
    end
    testServer1.vm.provision "shell", run: "always", inline: <<-SHELL
    ip route del default dev eth0
    ip route add default via 172.16.2.1 dev eth1
    SHELL
  end


  config.vm.define "testClient1" do |testClient1|
    testClient1.vm.hostname = "testClient1"
    testClient1.vm.network "private_network", adapter: 2, virtualbox__intnet: "Client"
    testClient1.vm.provider :virtualbox do |vb|
      vb.name = "testClient1"
      vb.memory = 256
    end
    testClient1.vm.provision "shell", run: "always", inline: <<-SHELL
    ip route del default dev eth0
    SHELL
  end

  config.vm.define "testServer2" do |testServer2|
    testServer2.vm.hostname = "testServer2"
    testServer2.vm.network "private_network", ip: "172.16.2.3", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "Server"
    testServer2.vm.network "private_network",adapter: 3, virtualbox__intnet: "Client"
    testServer2.vm.provider :virtualbox do |vb|
      vb.name = "testServer2"
      vb.memory = 256
    end
    testServer2.vm.provision "shell", run: "always", inline: <<-SHELL
    ip route del default dev eth0
    ip route add default via 172.16.2.1 dev eth1
    SHELL
  end


  config.vm.define "testClient2" do |testClient2|
    testClient2.vm.hostname = "testClient2"
    testClient2.vm.network "private_network", adapter: 2, virtualbox__intnet: "Client"
    testClient2.vm.provider :virtualbox do |vb|
      vb.name = "testClient2"
      vb.memory = 256
    end
    testClient2.vm.provision "shell", run: "always", inline: <<-SHELL
    ip route del default dev eth0
    SHELL
  end

end
