# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :Box => {
        :box_name => "centos/7",
        :box_version => "1804.02",
        :ip_addr => '192.168.11.101',
  },
}

Vagrant.configure("2") do |config|

    MACHINES.each do |boxname, boxconfig|
  
        config.vm.define boxname do |box|
  
            box.vm.box = boxconfig[:box_name]
            box.vm.host_name = boxname.to_s
            box.vm.network "private_network", ip: boxconfig[:ip_addr]
            box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
                    needsController = false
                end    
        config.vm.provision "file", source: "01.watchlog.sh", destination: "~/01.watchlog.sh"
        config.vm.provision "file", source: "02.spawn-fcgi.sh", destination: "~/02.spawn-fcgi.sh"
        config.vm.provision "file", source: "03.apache.sh", destination: "~/03.apache.sh"
        box.vm.provision "shell", inline: <<-SHELL
            mkdir -p ~root/.ssh
            cp ~vagrant/.ssh/auth* ~root/.ssh
            yum -y install epel-release
            yum -y install spawn-fcgi php php-cli
            bash /home/vagrant/01.watchlog.sh
            bash /home/vagrant/02.spawn-fcgi.sh
            bash /home/vagrant/03.apache.sh
       SHELL
  
      end
    end
  end
