---
# tasks file for nginx

- name: Install epel-release
  yum:
      name: epel-release
      state: latest

- name: Install nginx
  yum:
      name: nginx
      state: latest
  notify: start nginx

- name: Nginx startup configuring
  systemd:
    name: nginx
    state: started
    enabled: yes

- name: Put config
  template: src=nginx.j2 dest=/etc/nginx/nginx.conf owner=root mode=644
  notify: reload nginx

