---
# tasks file for web-srv
- name: Put SELinux in permissive mode, logging actions that would be blocked.
  selinux:
    policy: targeted
    state: permissive

- name: 'Put /etc/environment'
  copy:
    src: environment
    dest: /etc/environment
    group: root
    owner: root
    mode: 0644

- name: 'Install epel-release and vim'
  yum:
    name: ['epel-release', 'vim']
    state: latest

- name: 'Install PHP'
  yum:
    name: ['php', 'php-cli', 'php-gd', 'php-common', 'php-ldap', 'php-pdo', 'php-pear', 'php-snmp', 'php-xml', 'php-mysql', 'php-mbstring', 'php-fpm']
    state: latest

- name: 'Install Apache'
  yum:
    name: httpd
    state: latest

- name: 'Put httpd.conf config'
  copy:
    src: httpd.conf
    dest: /etc/httpd/conf/httpd.conf
    group: root
    owner: root
    mode: 0644

- name: 'Set timezone for PHP'
  shell: "echo 'date.timezone = Europe/Moscow' >> /etc/php.ini"

- name: 'Start httpd'
  systemd:
    name: httpd
    state: started
    enabled: yes


- name: 'Install git'
  yum:
    name: git
    state: latest

- name: 'Install phpipam'
  git:
    repo: https://github.com/phpipam/phpipam.git
    dest: /var/www/html/
    version: '1.4'

- name: 'Put priv.sh to /root/'
  copy:
    src: priv.sh
    dest: /root/
    mode: 0755

- name: 'Set privileges for /var/www/html'
  shell: 'bash /root/priv.sh'

- name: 'Put config.php'
  copy:
    src: config.php
    dest: /var/www/html/
