---
# tasks file for open-vpn

- name: Installing epel-release
  yum:
    name: epel-release
    state: latest

- name: Installing Open-vpn
  yum:
    name: openvpn
    state: latest

- name: Enabling ip forwarding
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: yes
    state: present
    reload: yes
