---
- hosts: server, client
  become: true
  roles:
    - open-vpn

- hosts: server
  become: true
  roles:
#    - open-vpn-server-tun
    - open-vpn-server-tap

- hosts: client
  become: true
  roles:
#    - open-vpn-client-tun
    - open-vpn-client-tap

#- hosts: all
#  become: true
#  roles:
#    - utility
