---
- hosts: server, client
  become: true
  roles:
    - open-vpn

- hosts: server
  become: true
  roles:
    - open-vpn-server

- hosts: client
  become: true
  roles:
    - open-vpn-client

- hosts: all
  become: true
  roles:
    - utility
