# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/vpn.yml"
    ansible.become = "true"
  end


  config.vm.define "vpn01" do |vpn01|
    vpn01.vm.network "private_network", ip: "10.0.0.10", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpn"
    vpn01.vm.network "private_network", ip: "172.16.1.1", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "local-1"
    vpn01.vm.hostname = "vpn01"
    config.vm.provider :virtualbox do |vb|
        vb.name = "vpn01"
	vb.memory = 256
    end
  end

  config.vm.define "vpn02" do |vpn02|
    vpn02.vm.hostname = "vpn02"
    vpn02.vm.network "private_network", ip: "10.0.0.20", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpn"
    vpn02.vm.network "private_network", ip: "172.16.2.1", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "local-2"
    config.vm.provider :virtualbox do |vb|
        vb.name = "vpn02"
	vb.memory = 256
    end
  end

end
