# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "centos/7"

  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/vpn.yml"
    ansible.become = "true"
  end


  config.vm.define "server" do |server|
    server.vm.hostname = "server"
    server.vm.network "private_network", ip: "10.0.0.10", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpn"
    server.vm.network "private_network", ip: "172.16.1.1", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "local-1"
    config.vm.provider :virtualbox do |vb|
#      vb.name = "server"
	  vb.memory = 256
    end
  end

  config.vm.define "client" do |client|
    client.vm.hostname = "client"
    client.vm.network "private_network", ip: "10.0.0.20", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "vpn"
    client.vm.network "private_network", ip: "172.16.2.1", adapter: 3, netmask: "255.255.255.0", virtualbox__intnet: "local-2"
    config.vm.provider :virtualbox do |vb|
#      vb.name = "client"
	  vb.memory = 256
    end
  end

  config.vm.define "pc1" do |pc1|
    pc1.vm.hostname = "pc1"
    pc1.vm.network "private_network", ip: "172.16.1.2", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-1"
    config.vm.provider :virtualbox do |vb|
#      vb.name = "pc1"
      vb.memory = 256
    end
    pc1.vm.provision "shell", run: "always", inline: <<-SHELL
    ip route del default dev eth0
    ip route add default via 172.16.1.1 dev eth1
    SHELL
  end


  config.vm.define "pc2" do |pc2|
    pc2.vm.hostname = "pc2"
    pc2.vm.network "private_network", ip: "172.16.2.2", adapter: 2, netmask: "255.255.255.0", virtualbox__intnet: "local-2"
    config.vm.provider :virtualbox do |vb|
#      vb.name = "pc2"
      vb.memory = 256
    end
    pc2.vm.provision "shell", run: "always", inline: <<-SHELL
    ip route del default dev eth0
    ip route add default via 172.16.2.1 dev eth1
    SHELL
  end

end
