---
# tasks file for routing

- name: 'Put daemons to /etc/frr/'
  template:
    src: daemons.j2
    dest: /etc/frr/daemons
    owner: frr
    group: frr
  notify: restart routing

#- name: 'Put daemons.conf to /etc/frr/'
#  copy:
#    src: daemons.conf
#    dest: /etc/frr/
#    owner: frr
#    group: frr

- name: 'Put frr.conf to /etc/frr/'
  template:
    src: frr.conf.j2
    dest: /etc/frr/frr.conf
    owner: frr
    group: frr
  notify: restart routing

- name: 'Put vtysh.conf'
  copy:
    src: vtysh.conf
    dest: /etc/frr/
    owner: frr
    group: frrvty
 
- name: 'Starting routing daemon frr'
  systemd:
    name: frr
    state: started
    enabled: yes
