# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES = {
 :nginx => {
        :box_name => "centos/7",
        :net => [
                   {adapter: 2, auto_config: false, virtualbox__intnet: true},
                ]
  },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

        box.vm.provider :virtualbox do |vb|
                    vb.customize ["modifyvm", :id, "--memory", "256"]
                end
        box.vm.box = boxconfig[:box_name]
        box.vm.host_name = boxname.to_s
        boxconfig[:net].each do |ipconf|
          box.vm.network "private_network", ipconf
        end
        box.vm.provision "shell", inline: <<-SHELL
          mkdir -p ~root/.ssh
                cp ~vagrant/.ssh/auth* ~root/.ssh
          echo "net.ipv4.ip_forward = 1" >> /etc/sysctl.conf
          sysctl -p /etc/sysctl.conf
        SHELL

      end
  end
  config.vm.network  "forwarded_port", guest: 8080, host: 8080, auto_correct: true
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/nginx.yml"
    ansible.become = "true"
  end
end
